# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Yielda Blog
subtitle: opening the kimono
description: Yielda is a Web3 social strategy game that is interesting, engaging, provably fair, and insanely profitable. Scheme like EVERYONE is watching!
url: https://blog.yielda.io
repository: yielda-game/yielda-game.github.io
email:
# description: >- # this means to ignore newlines until "baseurl:"
  we saw what you did there 
github_username: yielda-game
minimal_mistakes_skin: yielda
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 10 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from

author:
  # name   : "Yielda"
  avatar : "/assets/images/bio-photo.png"
  # bio    : "WAY too good to be true!"
  links:
    - label: "What is Yielda?"
      icon: "fa fa-fw fa-question-circle"
      url: "/blog/what-is-yielda/"
    - label: "Play Yielda!"
      icon: "fa fa-fw fa-play"
      url: "https://yielda.io"
    - label: "Try it on Testnet!"
      icon: "fa fa-fw fa-step-forward"
      url: "https://preview.yielda.io"
    - label: "Releases"
      icon: "fas fa-fw fa-cloud-upload-alt"
      url: "/blog/releases"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/yielda_game"
    - label: "Telegram"
      icon: "fab fa-fw fa-telegram"
      url: "https://t.me/yielda_game"
    - label: "Email"
      icon: "fa fa-fw fa-envelope"
      url: "mailto:hello@yielda.io"

footer:
  links:
    - label: "What is Yielda?"
      icon: "fa fa-fw fa-question-circle"
      url: "/blog/what-is-yielda/"
    - label: "Play Yielda!"
      icon: "fa fa-fw fa-play"
      url: "https://yielda.io"
    - label: "Try it on Testnet!"
      icon: "fa fa-fw fa-step-forward"
      url: "https://preview.yielda.io"
    - label: "Releases"
      icon: "fas fa-fw fa-cloud-upload-alt"
      url: "/blog/releases"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter"
      url: "https://twitter.com/yielda_game"
    - label: "Telegram"
      icon: "fab fa-fw fa-telegram"
      url: "https://t.me/yielda_game"
    - label: "Email"
      icon: "fa fa-fw fa-envelope"
      url: "mailto:hello@yielda.io"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      excerpt_separator: "<!--more-->"
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      show_date: true
      related: true
      toc: true
      toc_sticky: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/

tag_archive:
  type: liquid
  path: /tags/

comments:
  provider: "disqus"
  disqus:
    shortname: "yielda"

# Required to get the site to run locally.
github: [metadata]

analytics:
  provider: google-gtag
  google:
    tracking_id: G-VZPYPVPPQ4